### ISSUE TITLE
Multiple db connections initialized

### ISSUE THREAD

**Issue by LonJonn** [Jyuston/IoTBay#4]
A new DB Connection is created each time the DB is accessed. 
 
For example, in `LoginController.java`
```java
DBConnector connector = new DBConnector();
Connection conn = connector.openConnection();
DBManager db = new DBManager(conn);

Customer customer = db.findUserByEmailPass(email, password);

connector.closeConnection();
            
return customer;
```

 
We should look for a way to persist a connection to the DB instead.

**Comment by dennisz01** [comment]
Agreed. Connection pooling will be introduced in this week's workshop. Idk how to do it so for now I've just done it that way.
