### ISSUE TITLE
Move DBManager functionality?

### ISSUE THREAD

**Issue by LonJonn** [Jyuston/IoTBay#5]
Should the functionality currently within `DBManager.java` be moved to their respective files?
For example, `addCustomer()` could be a static method on the `Customer` class.
 
This would stop the `DBManager` getting overpopulated with functionality related to multiple parts of the application.

**Comment by dennisz01** [comment]
I was following the workshop example - the Db manager returns an instantiated class object (e.g. user).

But I see your point about cluttering. I would prefer to have seperate DBManager classes for different classes. E.g. dbmanager-cus for customer operations, dbmanager-product for product operations etc. Also I did research on DAO in MVC. The DAO classes by convention should return instantiated objects.

**Comment by LonJonn** [comment]
Yea the DAO still needs to return an instantiated object but we can still return instances from static methods. We could have something like 
```
call customer.find() static method
which would then search through the database
create an instance based on data
return that instance
```
But we can probs move the functionally to separate files like you said.

[this looks like a decent way to do that.](https://www.baeldung.com/java-dao-pattern)

So we would have a `__Dao.java` file for whatever we need. Looks pretty clean.

**Comment by dennisz01** [comment]
Looks good to me.
